# Generated by Django 5.2.7 on 2025-11-01 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(default='Pending', max_length=100)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_summary', to='sme.smeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('business_registration', 'Business Registration Certificate'), ('kra_pin', 'KRA PIN Certificate'), ('county_permit', 'County Business Permit'), ('nssf', 'NSSF Registration'), ('nhif', 'NHIF Registration'), ('tax_compliance', 'Tax Compliance Certificate')], max_length=50)),
                ('file', models.FileField(upload_to='compliance_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sme.smeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_result', to='compliance.document')),
            ],
        ),
    ]
