# Generated by Django 5.2.7 on 2025-10-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=255)),
                ('compliance_status', models.CharField(max_length=100)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
            ],
        ),
    ]
