# Generated by Django 5.2.7 on 2025-11-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancechecker',
            name='compliance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='compliancechecker',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
    ]
