# Generated by Django 5.2.7 on 2025-10-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancechecker',
            name='business_registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='compliance_docs/'),
        ),
        migrations.AddField(
            model_name='compliancechecker',
            name='environmental_clearance',
            field=models.FileField(blank=True, null=True, upload_to='compliance_docs/'),
        ),
        migrations.AddField(
            model_name='compliancechecker',
            name='fire_safety_certificate',
            field=models.FileField(blank=True, null=True, upload_to='compliance_docs/'),
        ),
        migrations.AddField(
            model_name='compliancechecker',
            name='health_safety_certificate',
            field=models.FileField(blank=True, null=True, upload_to='compliance_docs/'),
        ),
        migrations.AddField(
            model_name='compliancechecker',
            name='single_business_permit',
            field=models.FileField(blank=True, null=True, upload_to='compliance_docs/'),
        ),
        migrations.AddField(
            model_name='compliancechecker',
            name='tax_compliance_certificate',
            field=models.FileField(blank=True, null=True, upload_to='compliance_docs/'),
        ),
    ]
