# Generated by Django 5.2.7 on 2025-11-04 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_margin', models.FloatField(default=0)),
                ('expense_ratio', models.FloatField(default=0)),
                ('employee_efficiency', models.FloatField(default=0)),
                ('financial_health_index', models.FloatField(default=0)),
                ('market_resilience', models.FloatField(default=0)),
                ('funding_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('revenue_growth_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_analytics', to='sme.smeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('financial_goals', models.TextField(blank=True, null=True)),
                ('cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('savings_rate', models.FloatField(blank=True, null=True)),
                ('health_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='sme.smeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.financialrecord')),
            ],
        ),
    ]
