# Generated by Django 5.2.7 on 2025-10-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMEProfile',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=150)),
                ('employees', models.IntegerField()),
                ('annual_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tech_adoption_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('main_challenges', models.TextField()),
                ('digital_tools_used', models.TextField()),
                ('year_established', models.IntegerField()),
                ('growth_last_year', models.IntegerField()),
                ('funding_status', models.CharField(choices=[('Bootstrapped', 'Bootstrapped'), ('Seed Funded', 'Seed Funded'), ('Series A', 'Series A'), ('Series B+', 'Series B+')], max_length=100)),
                ('female_owned', models.BooleanField()),
                ('remote_work_policy', models.CharField(choices=[('None', 'None'), ('Partial', 'Partial'), ('Full', 'Full')], max_length=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('business_size', models.CharField(max_length=50)),
                ('ownership_type', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
