# Generated by Django 5.2.7 on 2025-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SME_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=50)),
                ('year_established', models.IntegerField()),
                ('ownership_type', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=150)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
