# Generated by Django 5.2.7 on 2025-11-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMEProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('year_established', models.IntegerField(blank=True, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('business_size', models.CharField(blank=True, max_length=50, null=True)),
                ('annual_revenue', models.FloatField(blank=True, null=True)),
                ('growth_last_year', models.FloatField(blank=True, null=True)),
                ('funding_status', models.CharField(blank=True, max_length=100, null=True)),
                ('ownership_type', models.CharField(blank=True, max_length=100, null=True)),
                ('female_owned', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('main_challenges', models.TextField(blank=True, null=True)),
                ('digital_tools_used', models.TextField(blank=True, null=True)),
                ('tech_adoption_level', models.CharField(blank=True, max_length=100, null=True)),
                ('remote_work_policy', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
