# Generated by Django 5.2.7 on 2025-11-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smeprofile',
            name='employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smeprofile',
            name='tech_adoption_level',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
    ]
