# Generated by Django 5.2.7 on 2025-10-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SME_Profile',
            new_name='SMEProfile',
        ),
    ]
